# Generated by Django 5.0.6 on 2024-06-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
    ]
